apiVersion: v1
kind: Pod
metadata:
  name: init-container
  labels:
    app.kubernetes.io/name: init-container
spec:
  containers:
  - name: app-c
    image: busybox:1.28
    command: ['sh', '-c', "echo App running! && sleep 3600"]
  initContainers:
  - name: initone
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup initone.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for initone; sleep 2; done"]
  - name: inittwo
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup inittwo.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for inittwo; sleep 2; done"]
