apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: dGhldXNlcg== 
  password: dGhlcGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: myothersecret
type: Opaque
stringData:
  username: theadminuser

# kubectl get secret myothersecret -o yaml
# kubectl get secret myothersecret -o jsonpath='{.data}'